server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:powerup_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:powerup_db}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

appDescription: "Pragma Powerup Reactive"
appVersion: "1.0.0"
